version: '3'

services:
  vipcommerce-app:
    #build: .
    image: ambientum/php:7.2-nginx
    container_name: vipcommerce-app
    depends_on:
      - vipcommerce-db
    ports:
      - 8000:8080
    volumes:
      - .:/var/www/app

  vipcommerce-db:
    image: mysql:5.7
    container_name: vipcommerce-db
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 96430409
      MYSQL_DATABASE: vipcommerce
      MYSQL_USER: vipcommerce
      MYSQL_PASSWORD: vipcommerce
    # DUMP ALL DATABASES: docker exec some-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql

volumes:
  postgresql_data:
    driver: local

